### ISSUE TITLE
Detect available languages before including generated ones

### ISSUE THREAD

**Issue by eskriett** [sourcegraph/go-ctags#6]
https://github.com/sourcegraph/zoekt makes use of `go-ctags`. When it's run with the latest version of `universal-ctags`, it breaks with the following error:

> starting /usr/bin/universal-ctags failed  with: Language "Thrift" already defined

The latest version of ctags defines the Thrift language: https://github.com/universal-ctags/ctags/tree/master/Units/parser-thrift.r

To improve handling of different version of universal-ctags, one approach might be to have `go-ctags` first  run `universal-ctags --list-languages` to determine which additional languages should be included which aren't already defined:

```
$ universal-ctags --list-languages | grep Thrift
Thrift
```

**Comment by keegancsmith** [comment]
Sorry I missed this report. This indeed is a good idea. In practice we consistently used a specific version at Sourcegraph so would update lists as we went so we never noticed this issue before. But now that others are depending on this we should make this more robust. Thanks, I'll timebox some time for this.

**Comment by keegancsmith** [comment]
This isn't the detection, but atleast unblocks you: https://github.com/sourcegraph/go-ctags/commit/96f4236

**Comment by keegancsmith** [comment]
This ends up being tricky to implement vs the cost of needing to update our mappings every once in a while. I am going to close this out and instead we track upstream ctags. If you need go-ctags to work on multiple ctags versions then you are welcome to contribute a PR / make your case more strongly :)
